current_version: 0.4.0

git_commit: True
git_tag: True

file_replaces:
  - path: setup.py
    search_template: version="{version}"
  - path: README.md
    search_template: "Current version: {version}"
