[tool.bumpytrack]
current_version = "1.0.0"
git_commit = true
git_tag = true

[[tool.bumpytrack.file_replaces]]
path = "setup.py"
search_template = "version=\"{version}\""

[[tool.bumpytrack.file_replaces]]
path = "README.md"
search_template = "Current version: {version}"

[[tool.bumpytrack.file_replaces]]
path = "bumpytrack/bumpytrack.py"
search_template = "Version: {version}"
